trigger:
- master

pool:
  name: 'Default'
  demands:
    - agent.name -equals Sergeys-MacBook-Air

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.401'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    dotnet restore --interactive
    dotnet build --configuration Release
  displayName: 'Restore and Build Project'

- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    dotnet test
  displayName: 'Run Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/HelloWorldApp/HelloWorldApp.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Create NuGet Package'

# Run dotnet nuget push with the --interactive flag for authentication
- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "https://pkgs.dev.azure.com/sergeygershov/infinity/_packaging/MyFeed/nuget/v3/index.json" --api-key az --interactive
  displayName: 'Publish Package to Azure Artifacts'

