trigger:
- master

pool:
  name: 'Default'
  demands:
    - agent.name -equals Sergeys-MacBook-Air

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.401'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore and build the project
- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    dotnet restore --interactive
    dotnet build --configuration Release
  displayName: 'Restore and Build Project'

# Print the version to the console
- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    VERSION=$(dotnet msbuild /t:GetVersion /nologo)
    echo "Build Version: $VERSION"
  displayName: 'Print Version to Console'

# Run tests
- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    dotnet test
  displayName: 'Run Tests'

# Pack the project, appending the build ID to the version to ensure unique version numbers
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/HelloWorldApp/HelloWorldApp.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    arguments: '--version-suffix $(Build.BuildId)'
  displayName: 'Create NuGet Package with Build Version'

# Push the package to Azure Artifacts securely using the PAT stored in a secret variable
- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "https://pkgs.dev.azure.com/sergeygershov/infinity/_packaging/MyFeed/nuget/v3/index.json" --api-key $(NuGet_Push)
  displayName: 'Push Package to Azure Artifacts'

# Publish the .nupkg files as pipeline artifacts so they are available for download
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'HelloWorldAppPackage'
    publishLocation: 'Pipeline'
  displayName: 'Publish NuGet Package as Pipeline Artifact'

