trigger:
- master

pool:
  name: 'Default'
  demands:
    - agent.name -equals Sergeys-MacBook-Air

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.401'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Restore and build the project
- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    dotnet restore --interactive
    dotnet build --configuration Release
  displayName: 'Restore and Build Project'

# Pack the project
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/HelloWorldApp/HelloWorldApp.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Create NuGet Package'

# Push the package to Azure Artifacts using the correct feed URL
- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "https://pkgs.dev.azure.com/sergeygershov/_packaging/sergeygershov/nuget/v3/index.json" --api-key $(NUGET_API_KEY)
  displayName: 'Push Package to Azure Artifacts'

# Optionally, publish the package as a pipeline artifact for review or debugging
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'HelloWorldAppPackage'
    publishLocation: 'Pipeline'
  displayName: 'Publish NuGet Package as Pipeline Artifact'

