trigger:
- master

pool:
  name: 'Default'
  demands:
    - agent.name -equals Sergeys-MacBook-Air

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.401'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Correct directory for restore and build
- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    dotnet restore --interactive
    dotnet build --configuration Release
  displayName: 'Restore and Build Project'

- script: |
    cd $(Build.SourcesDirectory)/HelloWorldApp
    dotnet test
  displayName: 'Run Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    projects: '$(Build.SourcesDirectory)/HelloWorldApp/HelloWorldApp.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Create NuGet Package'

# Publish the package using dotnet nuget push
- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source "MyFeed" --api-key az
  displayName: 'Publish Package to Azure Artifacts'

